/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author handy
 */
public class Detail_Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Withdraw
     */
    Connection conn;
    Statement stm;
    ResultSet rs;
    String id_transaksi, status;
    public Detail_Withdraw() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
    }
    
    public void setData(String id_transaksi){
        this.id_transaksi = String.valueOf(id_transaksi);
        try{
            rs = stm.executeQuery("SELECT * FROM transaksi t INNER JOIN user u ON t.ID_USER = u.ID_USER WHERE t.ID_TRANSAKSI = '"+id_transaksi+"'");
            rs.next();
            
            lb_id_transaksi.setText(rs.getString("id_transaksi"));
            lb_jenis_transaksi.setText(rs.getString("jenis_transaksi"));
            lb_total.setText(rs.getString("total_transaksi"));
            lb_waktu.setText(rs.getString("waktu_transaksi"));
            lb_status.setText(rs.getString("status"));
            lb_waktu_perubahan.setText(rs.getString("STATUS_CHANGE_TIME"));
            this.status = rs.getString("status");
//            this.id_user = rs.getInt("id_user");
//            this.total_transaksi = rs.getInt("total_transaksi");
//            this.jenis_transaksi = rs.getString("jenis_transaksi");
            
            rs = stm.executeQuery("SELECT * FROM transaksi t INNER JOIN konfirmasi_transaksi k ON t.ID_TRANSAKSI = k.ID_TRANSAKSI INNER JOIN user u ON k.ID_USER = u.ID_USER WHERE t.ID_TRANSAKSI = '"+id_transaksi+"'");
            if(rs.next()){
                lb_pengubah.setText(rs.getString("username"));
            }else{
                lb_pengubah.setText("");
            }            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_id_transaksi = new javax.swing.JLabel();
        lb_jenis_transaksi = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        lb_waktu = new javax.swing.JLabel();
        lb_status = new javax.swing.JLabel();
        lb_waktu_perubahan = new javax.swing.JLabel();
        lb_pengubah = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 488, 130, 40));

        lb_id_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_id_transaksi.setText("jLabel11");
        getContentPane().add(lb_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 224, 190, 20));

        lb_jenis_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_jenis_transaksi.setText("jLabel11");
        getContentPane().add(lb_jenis_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 266, 190, 20));

        lb_total.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_total.setText("jLabel11");
        getContentPane().add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 308, 190, 20));

        lb_waktu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_waktu.setText("jLabel11");
        getContentPane().add(lb_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 350, 190, 20));

        lb_status.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_status.setText("jLabel11");
        getContentPane().add(lb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 390, 190, 20));

        lb_waktu_perubahan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_waktu_perubahan.setText("jLabel11");
        getContentPane().add(lb_waktu_perubahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 433, 190, 20));

        lb_pengubah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_pengubah.setText("jLabel11");
        getContentPane().add(lb_pengubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 474, 190, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Detail Riwayat Penarikan.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Riwayat_Pesanan_Toko rw = new Riwayat_Pesanan_Toko();
        rw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if(status.equals("Berhasil")){
            try{
                // Report PDF
                String jrxmlFile = "src/Report/detail_transaksi.jrxml";
                HashMap param = new HashMap();
                param.put("ID_TRANSAKSI", String.valueOf(id_transaksi));
                JasperReport jspR = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, conn);
                String dest = "src/Report/detail_transaksi_"+id_transaksi+".pdf";
                JasperExportManager.exportReportToPdfFile(JPrint, dest);
                // End Report PDF
                JOptionPane.showMessageDialog(null, "File berhasil di-generate");
            }catch(JRException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Untuk mencetak detail transaksi, status transaksi harus berhasil!");
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_id_transaksi;
    private javax.swing.JLabel lb_jenis_transaksi;
    private javax.swing.JLabel lb_pengubah;
    private javax.swing.JLabel lb_status;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_waktu;
    private javax.swing.JLabel lb_waktu_perubahan;
    // End of variables declaration//GEN-END:variables
}
