/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author ASUS
 */
public class Detail_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Menu
     */
    
    Connection conn;
    Statement stm;
    ResultSet rs;
    int id;
    boolean isImageChanged = false;
    String asalFile = "";
    public Detail_Menu() {
        initComponents();
        initComponents();
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
    }
    
    private void pindahMenu(){
        Atur_Menu atur = new Atur_Menu();
        atur.setVisible(true);
        this.dispose();
    }
    
    public void setData(int id){
        this.id = id;
        try{
            rs = stm.executeQuery("SELECT * FROM menu WHERE id_menu = '"+id+"'");
            rs.next();
            txt_nama.setText(rs.getString("nama_menu"));
            txt_deskripsi.setText(rs.getString("deskripsi"));
            
            if(rs.getString("kategori").equals("Makanan")){
                cbKategori.setSelectedIndex(0);
            }else{
                cbKategori.setSelectedIndex(1);
            }
            
            txt_harga.setText(rs.getString("harga"));
            
            if(Integer.parseInt(rs.getString("tersedia")) == 1){
                rbTersedia.setSelected(true);
            }else{
                rbTidakTersedia.setSelected(true);
            }
            
            try {
            asalFile = rs.getString("gambar");    
            BufferedImage img = ImageIO.read(new File(asalFile));
            Image resizedImage = img.getScaledInstance(171, 171, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(resizedImage);
            lbl_gambar.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_gambar = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        txt_nama = new javax.swing.JTextField();
        txt_deskripsi = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        btn_ubahgambar = new javax.swing.JLabel();
        rbTidakTersedia = new javax.swing.JRadioButton();
        rbTersedia = new javax.swing.JRadioButton();
        btn_hapus = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbl_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 233, 171, 171));

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        getContentPane().add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 316, 300, -1));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 233, 300, -1));
        getContentPane().add(txt_deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 275, 300, -1));
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 358, 300, -1));

        btn_ubahgambar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubahgambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahgambarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ubahgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 410, 175, 30));

        buttonGroup1.add(rbTidakTersedia);
        rbTidakTersedia.setText("Tidak Tersedia");
        getContentPane().add(rbTidakTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 398, -1, -1));

        buttonGroup1.add(rbTersedia);
        rbTersedia.setText("Tersedia");
        getContentPane().add(rbTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 398, -1, -1));

        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 487, 100, 33));

        btn_ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ubahMouseEntered(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 487, 100, 33));

        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Detail Menu.png"))); // NOI18N
        BG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BGMouseClicked(evt);
            }
        });
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        pindahMenu();
    }//GEN-LAST:event_btn_backMouseClicked

    private void BGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BGMouseClicked

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        // TODO add your handling code here:
        String namaMenu = txt_nama.getText();
        String deskripsi = txt_deskripsi.getText();
        String kategori = cbKategori.getSelectedItem().toString();
        String harga = txt_harga.getText();
        int statusTersedia = 1;
        if(rbTersedia.isSelected() == true){
            statusTersedia = 1;
        }else{
            statusTersedia = 0;
        }
        
        if(!"".equals(namaMenu) && !"".equals(deskripsi) && !"".equals(kategori) && !"".equals(harga) && !"".equals(statusTersedia) && !"".equals(asalFile)){
            try{
                rs = stm.executeQuery("SELECT * FROM menu INNER JOIN toko ON menu.id_toko = toko.id_toko WHERE id_menu = '"+this.id+"'");
                rs.next();
                String fileLama = rs.getString("gambar");
                
                int index = asalFile.lastIndexOf('.');
                String jenisFile = asalFile.substring(index + 1);
                SimpleDateFormat formatter = new SimpleDateFormat("ddMMyyyy");
                Date date = new Date();
                Random rand = new Random();
                int namaFile = 1000+ rand.nextInt(9000);
                String linkFile = "src\\gambar\\"+formatter.format(date)+namaFile+rs.getString("id_toko")+"."+jenisFile;
                String link = linkFile.replace("\\", "\\\\");
                stm.executeUpdate("UPDATE menu SET nama_menu = '"+namaMenu+"', deskripsi = '"+deskripsi+"', gambar = '"+link+"', kategori='"+kategori+"', harga='"+harga+"', tersedia= '"+statusTersedia+"' WHERE id_menu = '"+id+"'");
                
                if(isImageChanged){
                    Files.delete(Paths.get(fileLama));
                    Files.copy(Paths.get(asalFile), Paths.get(linkFile));
                }else{
                    String oldLink = fileLama.replace("\\", "\\\\");
                    stm.executeUpdate("UPDATE menu SET gambar = '"+oldLink+"' WHERE id_menu = '"+id+"'");
                }
                
                JOptionPane.showMessageDialog(null, "Menu berhasil di-update");
                pindahMenu();
            }catch(SQLException | IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Semua data harus diisi terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_ubahgambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahgambarMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        try{
            File f = chooser.getSelectedFile();
            asalFile = f.getAbsolutePath();
            File gambar = new File(asalFile);
            BufferedImage img = ImageIO.read(gambar);
            Image resizedImage = img.getScaledInstance(171, 171, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(resizedImage);
            lbl_gambar.setIcon(icon);
            isImageChanged = true;
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(NullPointerException e){
            isImageChanged = false;
        }
    }//GEN-LAST:event_btn_ubahgambarMouseClicked

    private void btn_ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ubahMouseEntered

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here: 
        int confirmed = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Delete Confirmation Dialog", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            try {
                int result = stm.executeUpdate("UPDATE menu SET isDelete = '"+1+"' WHERE id_menu = '"+id+"'");
                if(result == 1){
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    pindahMenu();
                }else{
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_ubah;
    private javax.swing.JLabel btn_ubahgambar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel lbl_gambar;
    private javax.swing.JRadioButton rbTersedia;
    private javax.swing.JRadioButton rbTidakTersedia;
    private javax.swing.JTextField txt_deskripsi;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
