/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ASUS
 */
public class Detail_Riwayat_Penarikan extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Riwayat_Penarikan
     */
    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    public Detail_Riwayat_Penarikan() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
    }
    
    public void tampil_data(String id){
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Transaksi");
        table_data.addColumn("Nama User");
        table_data.addColumn("Jumlah Penarikan");
        table_data.addColumn("Waktu Penarikan");
        table_data.addColumn("Status");
        tbl_transaksi.setModel(table_data);
        try{
            rs = stm.executeQuery("SELECT t.id_transaksi, tk.nama_toko, t.total_transaksi, t.waktu_transaksi, t.status" 
                    + " FROM transaksi t" 
                    + " JOIN user u ON u.id_user = t.id_user"
                    + " JOIN toko tk ON tk.id_user = u.id_user"
                    + " WHERE t.id_user = '" + toko_login.id_user + "'"
                    + " ORDER BY t.waktu_transaksi DESC");
            while (rs.next()){
                Object[] data = new Object[5];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("nama_toko");
                data[2] = rs.getString("total_transaksi");
                data[3] = rs.getString("waktu_transaksi");
                data[4] = rs.getString("status");
                table_data.addRow(data);
                tbl_transaksi.setModel(table_data);
            }
            rs.close();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        btn_cetak = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        txt_waktu = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_nama_user = new javax.swing.JTextField();
        txt_id_transaksi = new javax.swing.JTextField();
        btn_back = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_transaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 780, 120));
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 488, 130, 40));

        txt_status.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_status.setToolTipText("");
        txt_status.setBorder(null);
        getContentPane().add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 270, 154, -1));

        txt_waktu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_waktu.setToolTipText("");
        txt_waktu.setBorder(null);
        getContentPane().add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 224, 154, -1));

        txt_jumlah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_jumlah.setToolTipText("");
        txt_jumlah.setBorder(null);
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 315, 154, -1));

        txt_nama_user.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_nama_user.setToolTipText("");
        txt_nama_user.setBorder(null);
        getContentPane().add(txt_nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 270, 154, -1));

        txt_id_transaksi.setEditable(false);
        txt_id_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_id_transaksi.setToolTipText("");
        txt_id_transaksi.setBorder(null);
        getContentPane().add(txt_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 224, 154, -1));

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Detail Riwayat Penarikan.png"))); // NOI18N
        BG.setToolTipText("");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Riwayat_Pesanan_Toko rp = new Riwayat_Pesanan_Toko();
        rp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void tbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_transaksiMouseClicked
        // TODO add your handling code here:
        int row = tbl_transaksi.getSelectedRow();
        String id_transaksi = tbl_transaksi.getValueAt(row, 0).toString();
        txt_id_transaksi.setText(id_transaksi);
        String nama_toko = tbl_transaksi.getValueAt(row, 1).toString();
        txt_nama_user.setText(nama_toko);
        String jumlah = tbl_transaksi.getValueAt(row, 2).toString();
        txt_jumlah.setText(jumlah);
        String waktu = tbl_transaksi.getValueAt(row, 3).toString();
        txt_waktu.setText(waktu);
        String status = tbl_transaksi.getValueAt(row, 4).toString();
        txt_status.setText(status);
    }//GEN-LAST:event_tbl_transaksiMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Riwayat_Penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Riwayat_Penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Riwayat_Penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Riwayat_Penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Riwayat_Penarikan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_close;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txt_id_transaksi;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_nama_user;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_waktu;
    // End of variables declaration//GEN-END:variables
}
