/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author ASUS
 */
public class Riwayat_Pesanan_Toko extends javax.swing.JFrame {

    /**
     * Creates new form Riwayat_Pesanan_Toko
     */
    Connection con;
    Statement stm;
    ResultSet rs;
    String id_toko;
    String nama_toko;

    public Riwayat_Pesanan_Toko() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
        tampil_data();
    }
    
    private void tampil_data() {
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("ID Transaksi");
        table_data.addColumn("Jenis Transaksi");
        table_data.addColumn("Total");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_riwayat.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT * FROM user INNER JOIN toko ON user.id_user = toko.id_user WHERE user.id_user='"+toko_login.getId_user()+"'");
            rs.next();
            this.id_toko = rs.getString("id_toko");
            this.nama_toko = rs.getString("nama_toko");
            
            rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"' ORDER BY transaksi.waktu_transaksi");
            
            while(rs.next()){
                Object[] data = new Object[5];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("jenis_transaksi");
                if(data[1].equals("Pembelian")){
                    data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                }else{
                    data[2] = rs.getString("total_transaksi");
                }
                data[3] = rs.getString("waktu_transaksi");
                data[4] = rs.getString("status");
                table_data.addRow(data);
                tbl_riwayat.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private String cekTanggal(){
        Date date = new Date();
        date = tanggalTransaksi.getDate();
        String tanggal = "";
        if(date != null){
            String tampilan ="yyyy-MM-dd" ; 
            SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
            tanggal = String.valueOf(fm.format(date));
        }
        
        return tanggal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tanggalTransaksi = new com.toedter.calendar.JDateChooser();
        btn_back = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        btn_detail = new javax.swing.JLabel();
        btn_penarikan = new javax.swing.JLabel();
        btn_tolak = new javax.swing.JLabel();
        btn_terima = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_riwayat = new javax.swing.JTable();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cetak");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));
        getContentPane().add(tanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 480, -1));

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        btn_detail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_detailMouseClicked(evt);
            }
        });
        getContentPane().add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 495, 115, 36));

        btn_penarikan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_penarikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penarikanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_penarikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 391, 80, 80));

        btn_tolak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tolak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tolakMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 306, 80, 80));

        btn_terima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_terima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_terimaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_terima, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 219, 80, 80));

        tbl_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 680, 280));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Riwayat Pesanan.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Menu_Toko mt = new Menu_Toko();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detailMouseClicked
        // TODO add your handling code here:
        if(tbl_riwayat.getSelectionModel().isSelectionEmpty() == false){
            int row = tbl_riwayat.getSelectedRow();
            String id = tbl_riwayat.getValueAt(row, 0).toString();
            String nama_user = tbl_riwayat.getValueAt(row, 1).toString();
            String jenis_transaksi = tbl_riwayat.getValueAt(row, 1).toString();
            
            if(jenis_transaksi.equals("Pembelian")){
                Detail_Riwayat_Pesanan r = new Detail_Riwayat_Pesanan();
                r.tampil_data(id, nama_user);
                r.setVisible(true);
                this.dispose();    
            }else{
                Detail_Riwayat_Penarikan rp = new Detail_Riwayat_Penarikan();
                rp.tampil_data(id);
                rp.setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan pilih pesanan terlebih dahulu!");
        }
        
    }//GEN-LAST:event_btn_detailMouseClicked

    private void btn_terimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terimaMouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            tampil_data();
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);
        
            try{
                rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE (transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"') AND transaksi.waktu_transaksi LIKE '"+cekTanggal()+"%' ORDER BY transaksi.waktu_transaksi");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    if(data[1].equals("Pembelian")){
                        data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                    }else{
                        data[2] = rs.getString("total_transaksi");
                    }
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_terimaMouseClicked

    private void btn_tolakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tolakMouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE (transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"') AND transaksi.jenis_transaksi = 'Pembelian' ORDER BY transaksi.waktu_transaksi");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    if(data[1].equals("Pembelian")){
                        data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                    }else{
                        data[2] = rs.getString("total_transaksi");
                    }
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE (transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"') AND transaksi.jenis_transaksi = 'Pembelian' AND transaksi.waktu_transaksi LIKE '"+cekTanggal()+"%' ORDER BY transaksi.waktu_transaksi");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    if(data[1].equals("Pembelian")){
                        data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                    }else{
                        data[2] = rs.getString("total_transaksi");
                    }
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_tolakMouseClicked

    private void btn_penarikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penarikanMouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE (transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"') AND transaksi.jenis_transaksi = 'Withdraw' ORDER BY transaksi.waktu_transaksi");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    if(data[1].equals("Pembelian")){
                        data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                    }else{
                        data[2] = rs.getString("total_transaksi");
                    }
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * FROM transaksi LEFT JOIN pembelian ON transaksi.ID_TRANSAKSI = pembelian.ID_TRANSAKSI WHERE (transaksi.ID_USER = '"+toko_login.getId_user()+"' OR pembelian.ID_TOKO = '"+this.id_toko+"') AND transaksi.jenis_transaksi = 'Withdraw' AND transaksi.waktu_transaksi LIKE '"+cekTanggal()+"%' ORDER BY transaksi.waktu_transaksi");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    if(data[1].equals("Pembelian")){
                        data[2] = String.valueOf(-rs.getInt("total_transaksi"));
                    }else{
                        data[2] = rs.getString("total_transaksi");
                    }
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_penarikanMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try{
            // Report PDF
            String jrxmlFile = "src/Report/riwayat_transaksi_toko.jrxml";
            HashMap param = new HashMap();
            param.put("ID_USER", String.valueOf(toko_login.getId_user()));
            param.put("ID_TOKO", this.id_toko);
            param.put("USERNAME", toko_login.getUsername());
            param.put("NAMA_TOKO", this.nama_toko);
            param.put("SALDO", String.valueOf(toko_login.getSaldo()));
            JasperReport jspR = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, con);
            String dest = "src/Report/riwayat_transaksi_toko"+toko_login.getId_user()+".pdf";
            JasperExportManager.exportReportToPdfFile(JPrint, dest);
            // End Report PDF
            JOptionPane.showMessageDialog(null, "File berhasil di-generate");
        }catch(JRException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Pesanan_Toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_detail;
    private javax.swing.JLabel btn_penarikan;
    private javax.swing.JLabel btn_terima;
    private javax.swing.JLabel btn_tolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tanggalTransaksi;
    private javax.swing.JTable tbl_riwayat;
    // End of variables declaration//GEN-END:variables
}