/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ASUS
 */
public class Riwayat_Pesanan_Toko extends javax.swing.JFrame {

    /**
     * Creates new form Riwayat_Pesanan_Toko
     */
    Connection con;
    Statement stm;
    ResultSet rs;

    public Riwayat_Pesanan_Toko() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
        tampil_data();
    }
    
    private void tampil_data() {
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Pembelian");
        table_data.addColumn("Nama Menu");
        table_data.addColumn("Jumlah");
        table_data.addColumn("Harga Total");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_pesanan.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT dp.id_detail_pembelian, m.nama_menu, dp.jumlah, dp.subtotal, t.waktu_transaksi, dp.status"
                    + " FROM detail_pembelian dp"
                    + " JOIN menu m ON m.id_menu = dp.id_menu"
                    + " JOIN pembelian p ON p.id_pembelian = dp.id_pembelian"
                    + " JOIN transaksi t ON t.id_transaksi = p.id_transaksi"
                    + " WHERE p.id_toko = (SELECT id_toko FROM toko WHERE id_user = '" + toko_login.id_user + "')"
                    + " ORDER BY t.waktu_transaksi DESC");
            
            while(rs.next()){
                Object[] data = new Object[6];
                data[0] = rs.getString("id_detail_pembelian");
                data[1] = rs.getString("nama_menu");
                data[2] = rs.getString("jumlah");
                data[3] = rs.getString("subtotal");
                data[4] = rs.getString("Waktu_transaksi");
                data[5] = rs.getString("status");
                table_data.addRow(data);
                tbl_pesanan.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        btn_menunggu = new javax.swing.JLabel();
        btn_tolak = new javax.swing.JLabel();
        btn_terima = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));
        getContentPane().add(btn_menunggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 419, 88, 88));
        getContentPane().add(btn_tolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 324, 88, 88));

        btn_terima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_terima, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 229, 88, 88));

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_pesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 670, 310));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Riwayat Pesanan.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Menu_Toko mt = new Menu_Toko();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Pesanan_Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Pesanan_Toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_menunggu;
    private javax.swing.JLabel btn_terima;
    private javax.swing.JLabel btn_tolak;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pesanan;
    // End of variables declaration//GEN-END:variables
}
