/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author handy
 */
public class Detail_Deposit extends javax.swing.JFrame {

    /**
     * Creates new form Detail_Deposit
     */
    Connection conn;
    Statement stm;
    ResultSet rs;
    String id_transaksi, status;
    public Detail_Deposit() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
    }
    
    public void setData(int id_transaksi){
        this.id_transaksi = String.valueOf(id_transaksi);
        try{
            rs = stm.executeQuery("SELECT * FROM transaksi t INNER JOIN user u ON t.ID_USER = u.ID_USER WHERE t.ID_TRANSAKSI = '"+id_transaksi+"'");
            rs.next();
            
            lb_id_transaksi.setText(rs.getString("id_transaksi"));
            lb_jenis_transaksi.setText(rs.getString("jenis_transaksi"));
            lb_total.setText(rs.getString("total_transaksi"));
            lb_waktu.setText(rs.getString("waktu_transaksi"));
            lb_status.setText(rs.getString("status"));
            lb_waktu_perubahan.setText(rs.getString("STATUS_CHANGE_TIME"));
            this.status = rs.getString("status");
//            this.id_user = rs.getInt("id_user");
//            this.total_transaksi = rs.getInt("total_transaksi");
//            this.jenis_transaksi = rs.getString("jenis_transaksi");
            
            rs = stm.executeQuery("SELECT * FROM transaksi t INNER JOIN konfirmasi_transaksi k ON t.ID_TRANSAKSI = k.ID_TRANSAKSI INNER JOIN user u ON k.ID_USER = u.ID_USER WHERE t.ID_TRANSAKSI = '"+id_transaksi+"'");
            if(rs.next()){
                lb_status_diubah.setText(rs.getString("username"));
            }else{
                lb_status_diubah.setText("");
            }            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        lb_id_transaksi = new javax.swing.JLabel();
        lb_jenis_transaksi = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        lb_waktu = new javax.swing.JLabel();
        lb_status = new javax.swing.JLabel();
        lb_waktu_perubahan = new javax.swing.JLabel();
        lb_status_diubah = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 550, 40, 40));
        getContentPane().add(lb_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 160, 40));
        getContentPane().add(lb_jenis_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 150, 30));
        getContentPane().add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 150, 30));
        getContentPane().add(lb_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 150, 30));
        getContentPane().add(lb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 150, 30));
        getContentPane().add(lb_waktu_perubahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 150, 30));
        getContentPane().add(lb_status_diubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 150, 30));

        btn_cetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 493, 130, 30));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Detai_Deposit.png"))); // NOI18N
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Riwayat_Transaksi transaksi = new Riwayat_Transaksi();
        transaksi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
        if(status.equals("Berhasil")){
            try{
                // Report PDF
                String jrxmlFile = "src/Report/detail_transaksi.jrxml";
                HashMap param = new HashMap();
                param.put("ID_TRANSAKSI", String.valueOf(id_transaksi));
                JasperReport jspR = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, conn);
                String dest = "src/Report/detail_transaksi_"+id_transaksi+".pdf";
                JasperExportManager.exportReportToPdfFile(JPrint, dest);
                // End Report PDF
                JOptionPane.showMessageDialog(null, "File berhasil di-generate");
            }catch(JRException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Untuk mencetak detail transaksi, status transaksi harus berhasil!");
        }
    }//GEN-LAST:event_btn_cetakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel lb_id_transaksi;
    private javax.swing.JLabel lb_jenis_transaksi;
    private javax.swing.JLabel lb_status;
    private javax.swing.JLabel lb_status_diubah;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_waktu;
    private javax.swing.JLabel lb_waktu_perubahan;
    private javax.swing.JLabel template;
    // End of variables declaration//GEN-END:variables
}
