/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Ajeng Niarti
 */
public class Detail_Transaksi extends javax.swing.JFrame {
Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    /**
     * Creates new form Detail_Transaksi
     */
    public Detail_Transaksi() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
    }

    public void tampil_data(String id_transaksi){
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Transaksi");
        table_data.addColumn("Nama Pemesan");
        table_data.addColumn("Nama Menu");
        table_data.addColumn("Jumlah");
        table_data.addColumn("Total Harga");
        table_data.addColumn("Status");
        tbl_detail.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT t.id_transaksi, pl.nama_pelanggan, m.nama_menu, dp.jumlah, dp.subtotal, t.status FROM pembelian p"
                    + " JOIN transaksi t ON t.id_transaksi = p.id_transaksi"
                    + " JOIN user u ON u.id_user = t.id_user"
                    + " JOIN pelanggan pl ON pl.id_user = u.id_user"
                    + " JOIN detail_pembelian dp ON dp.id_pembelian = p.id_pembelian"
                    + " JOIN menu m ON m.id_menu = dp.id_menu"
                    + " WHERE t.id_transaksi = '" + id_transaksi + "'"
                    + "AND t.id_user = '" + user_login.id_user + "'");
                    
            while (rs.next()){
                Object[] data = new Object[6];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("Nama_Pelanggan");
                data[2] = rs.getString("Nama_Menu");
                data[3] = rs.getString("Jumlah");
                data[4] = rs.getString("Subtotal");
                data[5] = rs.getString("Status");
                table_data.addRow(data);
                tbl_detail.setModel(table_data);
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        nama_pemesan = new javax.swing.JTextField();
        id_transaksi = new javax.swing.JTextField();
        nama_menu = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        total_harga = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_detail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 760, 110));

        nama_pemesan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nama_pemesan.setBorder(null);
        getContentPane().add(nama_pemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 273, 155, -1));

        id_transaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_transaksi.setBorder(null);
        getContentPane().add(id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 228, 155, -1));

        nama_menu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nama_menu.setBorder(null);
        getContentPane().add(nama_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 319, 155, -1));

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jumlah.setBorder(null);
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 228, 155, -1));

        total_harga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_harga.setBorder(null);
        getContentPane().add(total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 273, 155, -1));

        status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status.setBorder(null);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 319, 155, -1));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 130, 40));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toko/Detail_Riwayat_Pesanan.png"))); // NOI18N
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
    Riwayat_Transaksi transaksi = new Riwayat_Transaksi();
    transaksi.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void tbl_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailMouseClicked
        // TODO add your handling code here:
    int row = tbl_detail.getSelectedRow();
            String id_pembelian = tbl_detail.getValueAt(row, 0).toString();
            id_transaksi.setText(id_pembelian);
            String nama_user = tbl_detail.getValueAt(row, 1).toString();
            nama_pemesan.setText(nama_user);
            String nama_menu1 = tbl_detail.getValueAt(row, 2).toString();
            nama_menu.setText(nama_menu1);
            String jumlah1 = tbl_detail.getValueAt(row, 3).toString();
            jumlah.setText(jumlah1);
            String total_harga1 = tbl_detail.getValueAt(row, 4).toString();
            total_harga.setText(total_harga1);
            String status1 = tbl_detail.getValueAt(row, 5).toString();
            status.setText(status1);
    }//GEN-LAST:event_tbl_detailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_close;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_menu;
    private javax.swing.JTextField nama_pemesan;
    private javax.swing.JTextField status;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JLabel template;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
