/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import static User.user_login.saldo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author ASUS
 */
public class Menu_TopUp extends javax.swing.JFrame {

    /**
     * Creates new form Menu_TopUp
     */
    
    int tambah_saldo = 0;
    int total = 0;
    
    Connection conn;
    Statement stm;
    ResultSet rs;
    public Menu_TopUp() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
        
        int balance = user_login.getsaldo();
        String balanceS = Integer.toString(balance);
        
        String saldo1 = Integer.toString(saldo);
        tm_saldo.setText(balanceS);
        
        String user = user_login.getusername();
        String users = user;
        
        JLabel username1 = username;
        username.setText(users);
        
    }
    
    private void resetTextTotal(){
        total = 0;
        txt_total.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        tm_saldo = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        btn_50000 = new javax.swing.JLabel();
        btn_20000 = new javax.swing.JLabel();
        btn_10000 = new javax.swing.JLabel();
        btn_5000 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 50, 50));

        username.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 320, 40));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 100, 40));

        tm_saldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tm_saldo.setText("0");
        getContentPane().add(tm_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 254, 110, -1));

        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 513, 100, 36));

        btn_50000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_50000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_50000MouseClicked(evt);
            }
        });
        getContentPane().add(btn_50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 365, 147, 56));

        btn_20000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_20000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_20000MouseClicked(evt);
            }
        });
        getContentPane().add(btn_20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 365, 147, 56));

        btn_10000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_10000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_10000MouseClicked(evt);
            }
        });
        getContentPane().add(btn_10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 365, 147, 57));

        btn_5000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_5000MouseClicked(evt);
            }
        });
        getContentPane().add(btn_5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 365, 147, 57));

        txt_total.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_total.setText("0");
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 448, 120, 42));

        btn_hapus.setText("Hapus");
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 100, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Top-Up Menu.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Menu_User back = new Menu_User();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_5000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5000MouseClicked
        // TODO add your handling code here:
        tambah_saldo = 5000;
        total = total + tambah_saldo;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_5000MouseClicked

    private void btn_10000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_10000MouseClicked
        // TODO add your handling code here:
        tambah_saldo = 10000;
        total = total + tambah_saldo;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_10000MouseClicked

    private void btn_20000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_20000MouseClicked
        // TODO add your handling code here:
        tambah_saldo = 20000;
        total = total + tambah_saldo;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_20000MouseClicked

    private void btn_50000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_50000MouseClicked
        // TODO add your handling code here:
        tambah_saldo = 50000;
        total = total + tambah_saldo;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_50000MouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        resetTextTotal();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Menu_User back = new Menu_User();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // TODO add your handling code here:
        if(total > 0){
            int confirmed = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);
            
            if(confirmed == JOptionPane.YES_OPTION){
                try{
                    Calendar cal = Calendar.getInstance();
                    cal.getTime();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    String currentDate = sdf.format(cal.getTime());
                    int result = stm.executeUpdate("INSERT INTO transaksi(ID_USER, TOTAL_TRANSAKSI, JENIS_TRANSAKSI, WAKTU_TRANSAKSI, STATUS_CHANGE_TIME, STATUS) VALUES('"+user_login.getId_user()+"', '"+total+"', 'Deposit', '"+currentDate+"', '"+currentDate+"', 'Pending')");
                    if(result == 1){
                        JOptionPane.showMessageDialog(null, "Penambahan saldo berhasil diproses");
                        resetTextTotal();
                    }else{
                        JOptionPane.showMessageDialog(null, "Penambahan saldo gagal diproses");
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
                
        }else{
            JOptionPane.showMessageDialog(null, "Nominal top-up tidak boleh nol!");
        }
    }//GEN-LAST:event_btn_tambahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_TopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_TopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_TopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_TopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_TopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_10000;
    private javax.swing.JLabel btn_20000;
    private javax.swing.JLabel btn_5000;
    private javax.swing.JLabel btn_50000;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tm_saldo;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
