/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

/**
 *
 * @author ASUS
 */
public class Menu_Pilih_Kantin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pilih_Kantin
     */
    public Menu_Pilih_Kantin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JLabel();
        kantin1 = new javax.swing.JLabel();
        kantin2 = new javax.swing.JLabel();
        kantin3 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 12, 30, 30));

        kantin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin1MouseClicked(evt);
            }
        });
        getContentPane().add(kantin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 240, 240));

        kantin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin2MouseClicked(evt);
            }
        });
        getContentPane().add(kantin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 240, 240));

        kantin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin3MouseClicked(evt);
            }
        });
        getContentPane().add(kantin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 240, 240));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Menu Kantin.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kantin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin1MouseClicked
        // TODO add your handling code here:
        Pilih_Menu kantin1 = new Pilih_Menu();
        kantin1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kantin1MouseClicked

    private void kantin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin2MouseClicked
        // TODO add your handling code here:
        Pilih_Menu kantin2 = new Pilih_Menu();
        kantin2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kantin2MouseClicked

    private void kantin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin3MouseClicked
        // TODO add your handling code here:
        Pilih_Menu kantin3 = new Pilih_Menu();
        kantin3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kantin3MouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Pilih_Kantin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel kantin1;
    private javax.swing.JLabel kantin2;
    private javax.swing.JLabel kantin3;
    // End of variables declaration//GEN-END:variables
}
