/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Login.LoginPage;

/**
 *
 * @author ASUS
 */
public class Menu_User extends javax.swing.JFrame {

    /**
     * Creates new form Menu_User
     */
    public Menu_User() {
        initComponents();
        
        int balance = user_login.getsaldo();
        String balanceS = Integer.toString(balance);
        tm_saldo.setText(balanceS);
        
        
       
        lbl_username.setText(user_login.username);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salam = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        btn_pesan = new javax.swing.JLabel();
        btn_topup = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        tm_saldo = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        btn_riwayatpesanan = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 135, 128, 40));

        salam.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        salam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salam.setText("Selamat Datang");
        salam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(salam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 50));

        lbl_username.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_username.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 900, 50));

        btn_pesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pesanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 200, 240));

        btn_topup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_topup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_topupMouseClicked(evt);
            }
        });
        getContentPane().add(btn_topup, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 268, 203, 242));

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 12, 40, 30));

        tm_saldo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        getContentPane().add(tm_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 93, 120, 30));

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 150, 40));

        btn_riwayatpesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_riwayatpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_riwayatpesananMouseClicked(evt);
            }
        });
        getContentPane().add(btn_riwayatpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 265, 205, 242));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Menu Page.png"))); // NOI18N
        template.setNextFocusableComponent(this);
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        setSize(new java.awt.Dimension(900, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pesanMouseClicked
        // TODO add your handling code here:
        Menu_Pilih_Kantin pesan = new Menu_Pilih_Kantin();
        pesan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_pesanMouseClicked

    private void btn_topupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_topupMouseClicked
        // TODO add your handling code here:
        Menu_TopUp topup = new Menu_TopUp();
        topup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_topupMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
    LoginPage logout = new LoginPage();
    logout.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Pengaturan_Akun pa = new Pengaturan_Akun();
        pa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_riwayatpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_riwayatpesananMouseClicked
        // TODO add your handling code here:
    Riwayat_Transaksi riwayat = new Riwayat_Transaksi();
    riwayat.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_riwayatpesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_pesan;
    private javax.swing.JLabel btn_riwayatpesanan;
    private javax.swing.JLabel btn_topup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel salam;
    private javax.swing.JLabel template;
    private javax.swing.JLabel tm_saldo;
    // End of variables declaration//GEN-END:variables
}
