/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author ASUS
 */
public class Menu_Pilih_Kantin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pilih_Kantin
     */
    static String kantin=null;
    Connection conn;
    Statement stm;
    ResultSet rs;
    int[] isAvailable = new int[6];
    public Menu_Pilih_Kantin() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
        for(int i = 0; i < 6; i++){
            isAvailable[i] = 1;
        }
        cekKantin();
    }
    
    private void cekKantin(){
        try {
            rs = stm.executeQuery("SELECT blok.id_blok FROM toko RIGHT JOIN blok ON toko.id_blok = blok.id_blok WHERE toko.id_blok IS NULL");
            
            while(rs.next()){
                if(rs.getInt("id_blok") == 1){
                    isAvailable[0] = 0;
                    kantin1.setText("Tidak Tersedia");
                    kantin1.setOpaque(true);
                    kantin1.setBackground(new Color(0,0,0,150));
                }else if(rs.getInt("id_blok") == 2){
                    isAvailable[1] = 0;
                    kantin2.setText("Tidak Tersedia");
                    kantin2.setOpaque(true);
                    kantin2.setBackground(new Color(0,0,0,150));
                }else if(rs.getInt("id_blok") == 3){
                    isAvailable[2] = 0;
                    kantin3.setText("Tidak Tersedia");
                    kantin3.setOpaque(true);
                    kantin3.setBackground(new Color(0,0,0,150));
                }else if(rs.getInt("id_blok") == 4){
                    isAvailable[3] = 0;
                    kantin4.setText("Tidak Tersedia");
                    kantin4.setOpaque(true);
                    kantin4.setBackground(new Color(0,0,0,150));
                }else if(rs.getInt("id_blok") == 5){
                    isAvailable[4] = 0;
                    kantin5.setText("Tidak Tersedia");
                    kantin5.setOpaque(true);
                    kantin5.setBackground(new Color(0,0,0,150));
                }else if(rs.getInt("id_blok") == 6){
                    isAvailable[5] = 0;
                    kantin6.setText("Tidak Tersedia");
                    kantin6.setOpaque(true);
                    kantin6.setBackground(new Color(0,0,0,150));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private boolean cekAda(int index){
        if(isAvailable[index] == 0){
            return false;
        }else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        kantin1 = new javax.swing.JLabel();
        kantin2 = new javax.swing.JLabel();
        kantin3 = new javax.swing.JLabel();
        kantin4 = new javax.swing.JLabel();
        kantin5 = new javax.swing.JLabel();
        kantin6 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 12, 30, 30));

        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 50, 50));

        kantin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin1.setForeground(new java.awt.Color(255, 255, 255));
        kantin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin1MouseClicked(evt);
            }
        });
        getContentPane().add(kantin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 155, 183, 185));

        kantin2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin2.setForeground(new java.awt.Color(255, 255, 255));
        kantin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin2MouseClicked(evt);
            }
        });
        getContentPane().add(kantin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 155, 183, 185));

        kantin3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin3.setForeground(new java.awt.Color(255, 255, 255));
        kantin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin3MouseClicked(evt);
            }
        });
        getContentPane().add(kantin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 155, 183, 185));

        kantin4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin4.setForeground(new java.awt.Color(255, 255, 255));
        kantin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin4MouseClicked(evt);
            }
        });
        getContentPane().add(kantin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 350, 183, 185));

        kantin5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin5.setForeground(new java.awt.Color(255, 255, 255));
        kantin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin5MouseClicked(evt);
            }
        });
        getContentPane().add(kantin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 350, 183, 185));

        kantin6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kantin6.setForeground(new java.awt.Color(255, 255, 255));
        kantin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kantin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kantin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kantin6MouseClicked(evt);
            }
        });
        getContentPane().add(kantin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 350, 183, 185));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Menu Kantin.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kantin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin1MouseClicked
        // TODO add your handling code here:
        if(cekAda(0)){
            kantin = "1";
            Pilih_Menu kantin1 = new Pilih_Menu();
            kantin1.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin1MouseClicked

    private void kantin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin2MouseClicked
        // TODO add your handling code here:
        if(cekAda(1)){
            kantin = "2";
            Pilih_Menu kantin2 = new Pilih_Menu();
            kantin2.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin2MouseClicked

    private void kantin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin3MouseClicked
        // TODO add your handling code here:
        if(cekAda(2)){
            kantin = "3";
            Pilih_Menu kantin3 = new Pilih_Menu();
            kantin3.setVisible(true);
            this.dispose();    
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin3MouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        Menu_User back = new Menu_User();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void kantin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin4MouseClicked
        // TODO add your handling code here:
        if(cekAda(3)){
            kantin = "4";
            Pilih_Menu kantin4 = new Pilih_Menu();
            kantin4.setVisible(true);
            this.dispose(); 
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin4MouseClicked

    private void kantin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin5MouseClicked
        // TODO add your handling code here:
        if(cekAda(4)){
            kantin = "5";
            Pilih_Menu kantin5 = new Pilih_Menu();
            kantin5.setVisible(true);
            this.dispose();            
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin5MouseClicked

    private void kantin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kantin6MouseClicked
        // TODO add your handling code here:
        if(cekAda(5)){
            kantin = "6";
            Pilih_Menu kantin6 = new Pilih_Menu();
            kantin6.setVisible(true);
            this.dispose();            
        }else{
            JOptionPane.showMessageDialog(null, "Kantin tidak tersedia!");
        }
    }//GEN-LAST:event_kantin6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pilih_Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Pilih_Kantin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel kantin1;
    private javax.swing.JLabel kantin2;
    private javax.swing.JLabel kantin3;
    private javax.swing.JLabel kantin4;
    private javax.swing.JLabel kantin5;
    private javax.swing.JLabel kantin6;
    // End of variables declaration//GEN-END:variables
}
