/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Ajeng Niarti
 */
public class Riwayat_Transaksi extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form Riwayat_Transaksi
     */
    public Riwayat_Transaksi() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
        tampil_data();
    }
    
    
    private void tampil_data() {
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("ID Transaksi");
        table_data.addColumn("Jenis Transaksi");
        table_data.addColumn("Total");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_riwayat.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT * "
                    + " FROM transaksi t"
                    + " WHERE t.id_user =  '" + user_login.id_user + "'"
                    + " ORDER BY t.waktu_transaksi DESC");
            
            while(rs.next()){
                Object[] data = new Object[5];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("jenis_transaksi");
                data[2] = rs.getString("total_transaksi");
                data[3] = rs.getString("waktu_transaksi");
                data[4] = rs.getString("status");
                table_data.addRow(data);
                tbl_riwayat.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private String cekTanggal(){
        Date date = new Date();
        date = tanggalTransaksi.getDate();
        String tanggal = "";
        if(date != null){
            String tampilan ="yyyy-MM-dd" ; 
            SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
            tanggal = String.valueOf(fm.format(date));
        }
        
        return tanggal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggalTransaksi = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JLabel();
        btn_setortunai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_riwayat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_detail = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 650, -1));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 225, 90, 90));

        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseEntered(evt);
            }
        });
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 90, 90));

        btn_setortunai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setortunaiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_setortunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 416, 90, 90));

        tbl_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 670, 220));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 495, 115, 36));

        btn_detail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_detailMouseClicked(evt);
            }
        });
        getContentPane().add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 110, 30));

        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 10, 40, 40));

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Riwayat Pesanan.png"))); // NOI18N
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
    Menu_User home = new Menu_User();
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * "
                        + " FROM transaksi t"
                        + " WHERE t.id_user =  '" + user_login.id_user + "'"
                        + " AND t.jenis_transaksi = 'Pembelian'"
                        + " ORDER BY t.waktu_transaksi DESC");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    data[2] = rs.getString("total_transaksi");
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * "
                        + " FROM transaksi t"
                        + " WHERE t.id_user =  '" + user_login.id_user + "'"
                        + " AND t.jenis_transaksi = 'Pembelian'"
                        + " AND t.waktu_transaksi LIKE '"+cekTanggal()+"%'"
                        + " ORDER BY t.waktu_transaksi DESC");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    data[2] = rs.getString("total_transaksi");
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_setortunaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setortunaiMouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * "
                        + " FROM transaksi t"
                        + " WHERE t.id_user =  '" + user_login.id_user + "'"
                        + " AND t.jenis_transaksi = 'Deposit'"
                        + " ORDER BY t.waktu_transaksi DESC");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    data[2] = rs.getString("total_transaksi");
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);

            try{
                rs = stm.executeQuery("SELECT * "
                        + " FROM transaksi t"
                        + " WHERE t.id_user =  '" + user_login.id_user + "'"
                        + " AND t.jenis_transaksi = 'Deposit'"
                        + " AND t.waktu_transaksi LIKE '"+cekTanggal()+"%'"
                        + " ORDER BY t.waktu_transaksi DESC");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    data[2] = rs.getString("total_transaksi");
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_btn_setortunaiMouseClicked

    private void btn_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detailMouseClicked
        // TODO add your handling code here:
        if(tbl_riwayat.getSelectionModel().isSelectionEmpty() == false){
            int row = tbl_riwayat.getSelectedRow();
            String jenisTransaksi = String.valueOf(tbl_riwayat.getValueAt(row, 1));
            
            if(jenisTransaksi.equals("Deposit")){
                Detail_Deposit dd = new Detail_Deposit();
                dd.setData(Integer.parseInt(String.valueOf(tbl_riwayat.getValueAt(row, 0))));
                dd.setVisible(true);
                this.dispose();
            }else if(jenisTransaksi.equals("Pembelian")){
                String id_transaksi = tbl_riwayat.getValueAt(row, 0).toString();
                Detail_Transaksi detail = new Detail_Transaksi();
                detail.tampil_data(id_transaksi);
                detail.setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum memilih data pada tabel!");
        }
    }//GEN-LAST:event_btn_detailMouseClicked

    private void btn_pembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if("".equals(cekTanggal())){
            tampil_data();
        }else{
            DefaultTableModel table_data = new DefaultTableModel();
            table_data.addColumn("ID Transaksi");
            table_data.addColumn("Jenis Transaksi");
            table_data.addColumn("Total");
            table_data.addColumn("Tanggal Transaksi");
            table_data.addColumn("Status");
            tbl_riwayat.setModel(table_data);
        
            try{
                rs = stm.executeQuery("SELECT * "
                        + " FROM transaksi t"
                        + " WHERE t.id_user =  '" + user_login.id_user + "'"
                        + " AND t.waktu_transaksi LIKE '"+cekTanggal()+"%'"
                        + " ORDER BY t.waktu_transaksi DESC");

                while(rs.next()){
                    Object[] data = new Object[5];
                    data[0] = rs.getString("id_transaksi");
                    data[1] = rs.getString("jenis_transaksi");
                    data[2] = rs.getString("total_transaksi");
                    data[3] = rs.getString("waktu_transaksi");
                    data[4] = rs.getString("status");
                    table_data.addRow(data);
                    tbl_riwayat.setModel(table_data);
                }
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try{
                // Report PDF
                String jrxmlFile = "src/Report/riwayat_transaksi.jrxml";
                HashMap param = new HashMap();
                param.put("ID_USER", user_login.getId_user());
                param.put("USERNAME", user_login.getusername());
                param.put("SALDO", String.valueOf(user_login.getsaldo()));
                JasperReport jspR = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, con);
                String dest = "src/Report/riwayat_transaksi"+user_login.getId_user()+".pdf";
                JasperExportManager.exportReportToPdfFile(JPrint, dest);
                // End Report PDF
                JOptionPane.showMessageDialog(null, "File berhasil di-generate");
            }catch(JRException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_detail;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_setortunai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tanggalTransaksi;
    private javax.swing.JTable tbl_riwayat;
    private javax.swing.JLabel template;
    // End of variables declaration//GEN-END:variables
}
