/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Toko.Detail_Konfirmasi_Pesanan_Toko;
import Toko.Detail_Riwayat_Pesanan;
import Toko.toko_login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Ajeng Niarti
 */
public class Riwayat_Transaksi extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form Riwayat_Transaksi
     */
    public Riwayat_Transaksi() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.conn;
        stm = DB.stm;
        tampil_data();
    }
    
    
    private void tampil_data() {
        DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Transaksi");
        table_data.addColumn("Total Transaksi");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_riwayat.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT t.id_transaksi, t.total_transaksi, t.waktu_transaksi, t.status"
                    + " FROM detail_pembelian dp"
                    + " JOIN pembelian p ON p.id_pembelian = dp.id_pembelian"
                    + " JOIN transaksi t ON t.id_transaksi = p.id_transaksi"
                    + " JOIN user u ON u.id_user = t.id_user"
                    + " JOIN pelanggan pl ON pl.id_user = t.id_user"
                    + " WHERE t.id_user =  '" + user_login.id_user + "'"
                    + " ORDER BY t.waktu_transaksi DESC");
            
            while(rs.next()){
                Object[] data = new Object[4];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("total_transaksi");
                data[2] = rs.getString("waktu_transaksi");
                data[3] = rs.getString("status");
                table_data.addRow(data);
                tbl_riwayat.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pembelian = new javax.swing.JLabel();
        btn_setortunai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_riwayat = new javax.swing.JTable();
        btn_detail = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 260, 90, 90));

        btn_setortunai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setortunaiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_setortunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 360, 90, 80));

        tbl_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 670, 280));

        btn_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_detailMouseClicked(evt);
            }
        });
        getContentPane().add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 110, 30));

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 10, 40, 40));

        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 40, 40));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User/Riwayat Pesanan.png"))); // NOI18N
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
    Menu_User home = new Menu_User();
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
    DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Transaksi");
        table_data.addColumn("Total Transaksi");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_riwayat.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT t.id_transaksi, t.total_transaksi, t.waktu_transaksi, t.status"
                    + " FROM detail_pembelian dp"
                    + " JOIN pembelian p ON p.id_pembelian = dp.id_pembelian"
                    + " JOIN transaksi t ON t.id_transaksi = p.id_transaksi"
                    + " JOIN user u ON u.id_user = t.id_user"
                    + " JOIN pelanggan pl ON pl.id_user = t.id_user"
                    + " WHERE t.id_user =  '" + user_login.id_user + "'"
                            + "AND t.jenis_transaksi = 'Pembelian'"
                    + " ORDER BY t.waktu_transaksi DESC");
            
            while(rs.next()){
                Object[] data = new Object[4];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("total_transaksi");
                data[2] = rs.getString("waktu_transaksi");
                data[3] = rs.getString("status");
                table_data.addRow(data);
                tbl_riwayat.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_setortunaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setortunaiMouseClicked
        // TODO add your handling code here:
    DefaultTableModel table_data = new DefaultTableModel();
        table_data.addColumn("Id Transaksi");
        table_data.addColumn("Total Transaksi");
        table_data.addColumn("Tanggal Transaksi");
        table_data.addColumn("Status");
        tbl_riwayat.setModel(table_data);
        
        try{
            rs = stm.executeQuery("SELECT t.id_transaksi, t.total_transaksi, t.waktu_transaksi, t.status"
                    + " FROM detail_pembelian dp"
                    + " JOIN pembelian p ON p.id_pembelian = dp.id_pembelian"
                    + " JOIN transaksi t ON t.id_transaksi = p.id_transaksi"
                    + " JOIN user u ON u.id_user = t.id_user"
                    + " JOIN pelanggan pl ON pl.id_user = t.id_user"
                    + " WHERE t.id_user =  '" + user_login.id_user + "'"
                            + "AND t.jenis_transaksi = 'Deposit'"
                    + " ORDER BY t.waktu_transaksi DESC");
            
            while(rs.next()){
                Object[] data = new Object[4];
                data[0] = rs.getString("id_transaksi");
                data[1] = rs.getString("total_transaksi");
                data[2] = rs.getString("waktu_transaksi");
                data[3] = rs.getString("status");
                table_data.addRow(data);
                tbl_riwayat.setModel(table_data);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_setortunaiMouseClicked

    private void btn_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detailMouseClicked
        // TODO add your handling code here:
     if(tbl_riwayat.getSelectionModel().isSelectionEmpty() == false){
            int row = tbl_riwayat.getSelectedRow();
            String id_transaksi = tbl_riwayat.getValueAt(row, 0).toString();
            String nama_user = tbl_riwayat.getValueAt(row, 1).toString();
            Detail_Transaksi detail = new Detail_Transaksi();
            detail.tampil_data(id_transaksi);
            detail.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan pilih pesanan terlebih dahulu!");
        }
    }//GEN-LAST:event_btn_detailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_detail;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_setortunai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_riwayat;
    private javax.swing.JLabel template;
    // End of variables declaration//GEN-END:variables
}
