/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author handy
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    Connection conn;
    Statement stm;
    ResultSet rs;
    boolean isPrinted = false;
    String bulan1, tahun1;
    public Laporan() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
    }
    
    private String cekNull(String nilai){
        String ret;
        if(nilai != null){
            ret = nilai;
        }else{
            ret = "0";
        }
        return ret;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tfTahun = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbJmlPenjualan = new javax.swing.JLabel();
        lbJumlahTopUp = new javax.swing.JLabel();
        lbJmlPenarikan = new javax.swing.JLabel();
        lbTotalPenjualan = new javax.swing.JLabel();
        lbTotalTopUp = new javax.swing.JLabel();
        lbTotalPenarikan = new javax.swing.JLabel();
        lbTotalSaldo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbPengguna = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbToko = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Laporan");

        jLabel2.setText("Keluar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("Kembali");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("Cetak");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("Jumlah Penjualan");

        jLabel6.setText("Jumlah Top Up");

        jLabel7.setText("Jumlah Penarikan");

        jLabel8.setText("Total Penjualan");

        jLabel9.setText("Total Top Up");

        jLabel10.setText("Total Penarikan");

        jLabel12.setText("Total saldo user");

        jLabel13.setText("Bulan");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel14.setText("Tahun");

        tfTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTahunActionPerformed(evt);
            }
        });

        jLabel15.setText("Tampilkan");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setText("Clear");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        lbJmlPenjualan.setText("jLabel17");

        lbJumlahTopUp.setText("jLabel18");

        lbJmlPenarikan.setText("jLabel19");

        lbTotalPenjualan.setText("jLabel20");

        lbTotalTopUp.setText("jLabel21");

        lbTotalPenarikan.setText("jLabel22");

        lbTotalSaldo.setText("jLabel24");

        jLabel11.setText("Jumlah Pengguna");

        lbPengguna.setText("jLabel17");

        jLabel18.setText("Jumlah Toko");

        lbToko.setText("jLabel19");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbJumlahTopUp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lbJmlPenjualan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotalPenjualan)
                                    .addComponent(lbJmlPenarikan)
                                    .addComponent(lbTotalTopUp))))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lbTotalPenarikan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbToko)
                                    .addComponent(lbPengguna)
                                    .addComponent(lbTotalSaldo)))))
                    .addComponent(jLabel9))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(lbJmlPenjualan)
                    .addComponent(lbTotalPenarikan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbJumlahTopUp)
                    .addComponent(jLabel12)
                    .addComponent(lbTotalSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbJmlPenarikan)
                    .addComponent(jLabel11)
                    .addComponent(lbPengguna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbTotalPenjualan)
                    .addComponent(jLabel18)
                    .addComponent(lbToko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbTotalTopUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTahunActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Menu_Atur_Toko mat = new Menu_Atur_Toko();
        mat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if(!"".equals(tfTahun.getText())){
            int tahun = Integer.parseInt(tfTahun.getText());
            String bulan = cbBulan.getSelectedItem().toString();
            bulan1 = bulan;
            tahun1 = String.valueOf(tahun);
            int month;
            if(bulan.equals("Januari")){
                month = 1;
            }else if(bulan.equals("Februari")){
                month = 2;
            }else if(bulan.equals("Maret")){
                month = 3;
            }else if(bulan.equals("April")){
                month = 4;
            }else if(bulan.equals("Mei")){
                month = 5;
            }else if(bulan.equals("Juni")){
                month = 6;
            }else if(bulan.equals("Juli")){
                month = 7;
            }else if(bulan.equals("Agustus")){
                month = 8;
            }else if(bulan.equals("September")){
                month = 9;
            }else if(bulan.equals("Oktober")){
                month = 10;
            }else if(bulan.equals("November")){
                month = 11;
            }else if(bulan.equals("Desember")){
                month = 12;
            }else{
                month = 0;
            }
            try{
                if(month != 0){
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_penjualan FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Pembelian'");
                    rs.next();
                    lbJmlPenjualan.setText(rs.getString("jumlah_penjualan"));
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_topup FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Deposit'");
                    rs.next();
                    lbJumlahTopUp.setText(rs.getString("jumlah_topup"));
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_withdraw FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Withdraw'");
                    rs.next();
                    lbJmlPenarikan.setText(rs.getString("jumlah_withdraw"));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_jual FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Pembelian'");
                    rs.next();
                    lbTotalPenjualan.setText(cekNull(rs.getString("total_jual")));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_topup FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Deposit'");
                    rs.next();
                    lbTotalTopUp.setText(cekNull(rs.getString("total_topup")));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_withdraw FROM transaksi WHERE status != 'Pending' AND MONTH(waktu_transaksi) = '"+month+"' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Withdraw'");
                    rs.next();
                    lbTotalPenarikan.setText(cekNull(rs.getString("total_withdraw")));
                }else{
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_penjualan FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Pembelian'");
                    rs.next();
                    lbJmlPenjualan.setText(rs.getString("jumlah_penjualan"));
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_topup FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Deposit'");
                    rs.next();
                    lbJumlahTopUp.setText(rs.getString("jumlah_topup"));
                    rs = stm.executeQuery("SELECT COUNT(*) AS jumlah_withdraw FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Withdraw'");
                    rs.next();
                    lbJmlPenarikan.setText(rs.getString("jumlah_withdraw"));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_jual FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Pembelian'");
                    rs.next();
                    lbTotalPenjualan.setText(cekNull(rs.getString("total_jual")));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_topup FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Deposit'");
                    rs.next();
                    lbTotalTopUp.setText(cekNull(rs.getString("total_topup")));
                    rs = stm.executeQuery("SELECT SUM(total_transaksi) AS total_withdraw FROM transaksi WHERE status != 'Pending' AND YEAR(waktu_transaksi) = '"+tahun+"' AND jenis_transaksi = 'Withdraw'");
                    rs.next();
                    lbTotalPenarikan.setText(cekNull(rs.getString("total_withdraw")));
                }
                
                rs = stm.executeQuery("SELECT SUM(saldo) AS total_saldo FROM user WHERE isdelete = 0");
                rs.next();
                lbTotalSaldo.setText(rs.getString("total_saldo"));
                rs = stm.executeQuery("SELECT COUNT(*) AS total_user FROM user INNER JOIN pelanggan ON user.id_user = pelanggan.id_user WHERE user.isdelete = 0");
                rs.next();
                lbPengguna.setText(rs.getString("total_user"));
                rs = stm.executeQuery("SELECT COUNT(*) AS total_toko FROM user INNER JOIN toko ON user.id_user = toko.id_user WHERE user.isdelete = 0");
                rs.next();
                lbToko.setText(rs.getString("total_toko"));
                isPrinted = true;
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi terlebih dahulu");
        }
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        lbJmlPenjualan.setText("");
        lbJumlahTopUp.setText("");
        lbJmlPenarikan.setText("");
        lbTotalPenjualan.setText("");
        lbTotalTopUp.setText("");
        lbTotalPenarikan.setText("");
        lbTotalSaldo.setText("");
        lbPengguna.setText("");
        lbToko.setText("");
        bulan1 = null;
        tahun1 = null;
        isPrinted = false;
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(isPrinted){
            try{
                // Report PDF
                String jrxmlFile = "src/Report/laporan.jrxml";
                HashMap param = new HashMap();
                param.put("JUMLAH_PENJUALAN", lbJmlPenjualan.getText());
                param.put("JUMLAH_TOPUP", lbJumlahTopUp.getText());
                param.put("JUMLAH_PENARIKAN", lbJmlPenarikan.getText());
                param.put("TOTAL_PENJUALAN", lbTotalPenjualan.getText());
                param.put("TOTAL_TOPUP", lbTotalTopUp.getText());
                param.put("TOTAL_PENARIKAN", lbTotalPenarikan.getText());
                param.put("TOTAL_SALDO", lbTotalSaldo.getText());
                param.put("JUMLAH_PENGGUNA", lbPengguna.getText());
                param.put("JUMLAH_TOKO", lbToko.getText());
                param.put("USERNAME_ADMIN", admin_login.getUsername());
                param.put("BULAN", bulan1);
                param.put("TAHUN", tahun1);
                JasperReport jspR = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, conn);
                String dest = "src/Report/laporan.pdf";
                JasperExportManager.exportReportToPdfFile(JPrint, dest);
                // End Report PDF
                JOptionPane.showMessageDialog(null, "File berhasil di-generate");
            }catch(JRException e){
                JOptionPane.showMessageDialog(null, e);
            }
                
        }else{
            JOptionPane.showMessageDialog(null, "Anda harus menampilkan data terlebih dahulu!");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbJmlPenarikan;
    private javax.swing.JLabel lbJmlPenjualan;
    private javax.swing.JLabel lbJumlahTopUp;
    private javax.swing.JLabel lbPengguna;
    private javax.swing.JLabel lbToko;
    private javax.swing.JLabel lbTotalPenarikan;
    private javax.swing.JLabel lbTotalPenjualan;
    private javax.swing.JLabel lbTotalSaldo;
    private javax.swing.JLabel lbTotalTopUp;
    private javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
